---
- name: Cordon node
  command: >-
    {{ bin_dir }}/kubectl cordon
    {{ kube_override_hostname|default(inventory_hostname) }}
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  changed_when: false

- name: Wait for node to cordon
  command: >-
    {{ bin_dir }}/kubectl get node
    {{ kube_override_hostname|default(inventory_hostname) }}
    -o json
  register: wait_for_cordon
  retries: 5
  delay: 20
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  changed_when: false
  until: (wait_for_cordon['stdout'] | from_json).spec.unschedulable

- name: Drain node
  command: >-
    {{ bin_dir }}/kubectl drain
    --force
    --ignore-daemonsets
    --grace-period {{ drain_grace_period }}
    --timeout {{ drain_timeout }}
    --delete-emptydir-data {{ kube_override_hostname|default(inventory_hostname) }}
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  changed_when: false
