---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.9
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    rbac:
      create: true
      impersonationResourceNames: ["wego-admin", "wego-readonly", "admin"]
      impersonationResources: ["groups", "users"]
      additionalRules:
        - apiGroups: ["infra.contrib.fluxcd.io"]
          resources: ["terraforms"]
          verbs: [ "get", "list", "patch" ]
    replicaCount: 2
    service:
      create: true
      port: 9001
    adminUser:
      create: true
      username: wego-admin
      createSecret: true
    metrics:
      enabled: true
    networkPolicy:
     create: false
  valuesFrom:
    - kind: Secret
      name: weave-gitops
      valuesKey: adminPassword
      targetPath: adminUser.passwordHash