apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops
    namespace: weave-gitops
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:n7P+OL3XqnDBUzvt,iv:mTlEpFDw+QPV233i3FaDioElzQF2lO+/yvzbVc5dMo0=,tag:02LAOrQdmWcslBDlhPVsGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZU1wTnVqb05EL1JxTmxs
            NGpJNjhSeWlsdkQxNHJNVVlnZ1RyZmZhOVVvCks0TUlMTjVEbjRWYVA0K1dPWExh
            SDZXektqZHJQWlFQNll5TlVsZnlLa3cKLS0tIDVKYVQwY203VUJ2WnlPUXlPRWR1
            YWZ1MkNwQkRFRWVLTC9PQTFLbU5ncUEKaiFuhkA01ap+EgzHEi3RxyN0B7i0So/9
            b17TG2lQzXUFA2eaJpx8TND813QQu45C6lv4zP4pgTPsa4Ivw9mf8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-13T19:32:00Z"
    mac: ENC[AES256_GCM,data:eM0nADYtqyAX9m5lx8srWH9k4IbTkomynXjOlpmO38DXBrV776k9DQ4Nf2o+eY+5VTzM5YyLXTQ/ll3UpdKmDBM+mnWhKdbCBXqtpNxMIG5ZIA//4fA4X4TQkJy5NNTDtTd3aOvCY+Q8vQq648A9Dkca8UBx9ntad1cMHJ5RYLc=,iv:ENa1GDJjj2MdWbCNEf4RhHwXV0rC+0uFKGogTkEtyKI=,tag:ihXDvUDXUP2UdrFUH/SfnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
