---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 2.32.4
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: velero/velero
      tag: v1.10.0
      resticTimeout: 6h
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
     existingSecret: s3-velero-eu-west-2
    configuration:
      extraEnvVars:
        TZ: "${TZ}"
      provider: aws
      backupStorageLocation:
        name: default
        bucket: home-lab-velero-backup
        default: true
        config:
          region: eu-west-2
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    snapshotsEnabled: false
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 1500Mi
          cpu: null
    schedules:
      daily-backup:
        schedule: 0 6 * * *
        template:
          ttl: 336h
          includedNamespaces:
           - uptimekuma
           - heimdall 
