apiVersion: v1
kind: Secret
metadata:
    name: s3-velero-eu-west-2
    namespace: velero
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IkWrQtB45fixIqd48571KN41hgs=,iv:GwILAz31HWr7NxQVGEk3rAs42drhfngEqUJLzHstgKw=,tag:ye80qa32MtauNHjyqQH6tQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SSewK+vZIF3TLAjAT5yzUfquQzM7SXbA7ofjr62Dw7YjBKmxAfnMzg==,iv:uYO46ve7ONSiUSvvkpCxBo0E7LS3O8AWuZ2X3EdtWKk=,tag:judc7oCOcTSlo+zFWTgQyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4blRWZFZ0eEZXOG1naVZ5
            MXNZVEFwQWpwK0JJdzJxT1J5Ny9LK0t2TldNCjlnNnpqeUZxQmlXOVZrTW9rLzJq
            anJ3TXM1N25YYzZOR3BXYi92Wjl5K0kKLS0tIHJFdnpWcjVDYThkQS9nd2M1S2Uy
            Z0h4RDh1T29OUHRiYnM2MzZLQ2QrYzgKDuzkQj0c4nnzVDCJG2vC0zTsQqiLxiFb
            V4yJzZz5A0qANEfmYJLi9qko7bidAxOJ2ZhhbR+hBau7/wr/cdYo3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-05T18:15:44Z"
    mac: ENC[AES256_GCM,data:5feQLB4lw0b75W/X4A7exMFvtRVfVAxOwuMIFzLPm0ncp9nmk7cCVG485dqi0LvYbelrPlW6PzqJO1QmnrM7a7ghkvg4SadOK1LMP3th03Zmq37LitWvJ1EBssLSYZ/RYiQcRDBWfgI2dcmB2b63xJQZKBCVWxaNB9620vqAf54=,iv:YuhFRV0cwqe5mQzmyTMSU+HdoabdNkzLB4stTCkIYGA=,tag:n1ZuGU7RsaaNn1SXVXUu8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
