### Update and install base packages
    - name: update packages
      apt:
        name: '*'
        state: latest
        update_cache: true
    - name: install curl
      apt:
        name:
           'curl'
        state: latest
    - name: install nfs-common
      apt:
        name:
          'nfs-common'
        state: latest
#### SSH Key install
    - name: check if already installed
      stat:
        path: /tmp/id_rsa_boot_k3s
      delegate_to: localhost
      become: false
      register: keypair_stat_result
### gen new keypair
    - name: 'Generate an OpenSSH keypair with the default values (4096 bits, rsa)'
      become: false
      community.crypto.openssh_keypair: null
      path: /tmp/id_rsa_boot_k3s
      delegate_to: localhost
      when: keypair_stat_result.stat.exists == false
### install new privkey
    - name: upload privkey to master
      become: false
      copy:
        src: /tmp/id_rsa_boot_k3s
        dest: ~/.ssh/id_rsa
### uploade pubkey
    - name: upload pubkey to master
      become: false
      copy:
        src: /tmp/id_rsa_boot_k3s.pub
        dest: ~/.ssh/id_rsa.pub
### made key authorized
    - name: add pubkey to servers
      become: false
      ansible.posix.authorized_key:
        user: '{{ ansible_user }}'
        state: present
        key: '{{ lookup(''file'', ''/tmp/id_rsa_boot_k3s.pub'') }}'
        path: '/home/{{ ansible_user }}/.ssh/authorized_keys'
        manage_dir: true
      register: output
### set output to debug      
    - name: debug
      debug: 'msg="{{ output }}'