apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik
type: Opaque
data:
    users: ENC[AES256_GCM,data:QwJUBcS+oHSyp8DgGo4TGKKsO+utNnkt3XI8gUnpXiKbyScVNDV4GYPHEke3b0Z3nQQeQBcpSINjU9+Fx2rOGQ==,iv:5349151GcKDznKeEkfckVqHPXMZrhJ80zXG6jgejYbw=,tag:B+ntFNi9dUIAVQi4dsB3SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUmhyYkJsZEZzcWViM0RP
            dVhYdEV1WFJVMGRNUDVvY0JjMHNTMkpDZ2s0Cm9SdzBNZjJqdDRWcmswdlRGWW5Y
            VHRhaE1OaEp5WmxFbXdzUzhFMSsxRlEKLS0tIFY3LzYvYXVUNGZNTjRBK0xHY1h3
            Z1VvUjNoRzRmTm0wWjMvaGlkWlFOd00KkGhLJFYdimuCaea+Iv3xbfT6Mcfeo7zW
            k24MD2NrnyBfCb6NvUFkpTce5eFdDsai3OjzbMignbYcZznxRIQYtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T23:15:14Z"
    mac: ENC[AES256_GCM,data:6AQKymxY8LU7JPBEUziQ2rZe+YwL3iKcDchmWpwlXi+Xxj1gBS1CHlWhsnwSh5JW2L6iVCsST/kkL3drZWaKNIgzIdt1ts0Ko3GsXOtHhnFN6eCGw+lzotwXkLNuFbHKejeyu9xhFqeJPNbEo4Uw5JP6l+3hLsy7ZuRwsvVrphA=,iv:PFZuwwxfrclgqoyp34dhzxGvvNgQnT4rAvF8sxuw+wk=,tag:hHL17Qf6udC0sRCD4qDnmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
