apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik
type: Opaque
data:
    users: ENC[AES256_GCM,data:fQ5X4YmRhzgdyaTCABL5raNsUpPJBLW7pBP+li8XVLtzbsAeeIqLYOESXp63I8V+BEBo4IbOdMYOptTb,iv:RxeJL1S3Ztn5Zsww1/FpLPm0V3zfOo/9m0L/z2leCXI=,tag:9yOAmrHC55bWq85J8i6WSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUmhyYkJsZEZzcWViM0RP
            dVhYdEV1WFJVMGRNUDVvY0JjMHNTMkpDZ2s0Cm9SdzBNZjJqdDRWcmswdlRGWW5Y
            VHRhaE1OaEp5WmxFbXdzUzhFMSsxRlEKLS0tIFY3LzYvYXVUNGZNTjRBK0xHY1h3
            Z1VvUjNoRzRmTm0wWjMvaGlkWlFOd00KkGhLJFYdimuCaea+Iv3xbfT6Mcfeo7zW
            k24MD2NrnyBfCb6NvUFkpTce5eFdDsai3OjzbMignbYcZznxRIQYtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T00:18:20Z"
    mac: ENC[AES256_GCM,data:WhYxnUvVN/RUlEK6ONxym00KvRefG864jud8S9xLYUtxYn7t4y6bD4UrYqgMVnIQTZjRl0jI4foO2JgU2ru0zu+BKb9mBFyC+VkchdP+8iFyOO9JrY2ixVWl4UyDz/AfUzNxOiVo7gG6kU5Pw3hig5OcVM4e9l6Auk9Q3QfmEHA=,iv:WS8kM76YWdQ6JI/ldMLEIPqaIuyeQATsS99Vqja8/hw=,tag:5Avl9iiTGvbdQ8F6PkXrcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
