apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: traefik
type: Opaque
data:
    users: ENC[AES256_GCM,data:C3xIckHuFJY180HEE5YgLpRXHS/E47J9ElhKxB1WuiIjvJqI2dUObIyv9HsYqv5KPYXvTcBKICc5P2Y=,iv:NfB8vyNw99rVBddQVCH8kedABTyd32t6hh/+NqwKC/c=,tag:jH6pqywViVDKwdAU3zwC+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUmhyYkJsZEZzcWViM0RP
            dVhYdEV1WFJVMGRNUDVvY0JjMHNTMkpDZ2s0Cm9SdzBNZjJqdDRWcmswdlRGWW5Y
            VHRhaE1OaEp5WmxFbXdzUzhFMSsxRlEKLS0tIFY3LzYvYXVUNGZNTjRBK0xHY1h3
            Z1VvUjNoRzRmTm0wWjMvaGlkWlFOd00KkGhLJFYdimuCaea+Iv3xbfT6Mcfeo7zW
            k24MD2NrnyBfCb6NvUFkpTce5eFdDsai3OjzbMignbYcZznxRIQYtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-27T23:31:47Z"
    mac: ENC[AES256_GCM,data:RxxBpeyEqGVNS4Bn+0tCePZpgTBrQ35htFxMGYC6Fjb4o8UvwUBNeTi6uagWGzxK6GNexRSN2aNWNnRF+Jo7SmT2rn7Y3P5itf46qH/2Cg0hztLJAVLOx3sRylsYpVFREDi4X0QdmlaLAh+7i1J50WmbeMlbK0u0OEVm2749m50=,iv:qdDo224O2qHC5UZoz38vQco9C9Yd0jAnub5yCI0vWfQ=,tag:gbZAPPopykCI+dd9tiV1OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
