# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_INT_DOMAIN: ENC[AES256_GCM,data:mJfHrzawJBODnnwWIf1OtKMa,iv:5ocIZ9Q8nCOFnumFIxLmrMRxvmMI6VCI1TR7kS3zmv8=,tag:Z/hxwhORVgqKWixTjKfq2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTHVZZVVXM1pUWUttTU95
            VzZPYTZTRzRNUE1nQ1JsbVlZa25ZZXdydmtZCmlNYVVydFRMaThzYnFDdWUySXIr
            Nm1BZVZDK1UwUnFIOXNHT1RwN2hNRTQKLS0tIEZEN3orMEFLK2hKMXY2UFJlUHdw
            TWw2NjhJM0ZkYnVqNVF5blNHd1lEWm8KUjKmesopbFq9fmAF7uyCUKOo8seXku58
            bath6Y2Sc1Kuqof2k67Jn/8CzjTvJsgjuLhr6bpkY2ARaexsPu0f/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-30T18:53:20Z"
    mac: ENC[AES256_GCM,data:PycCN8IHluvkwPgfFsKdGDwRlli3Meg14NGcCxUikUMov3J3U+tAMByq6YDCHRDYpNadiTonBmSqFgJE3qyudSsOuG8CvhnDAdL1q0nd0eIcyU54o7pr6igfYs1VfUhXLtCRXlpPq4HZ5Dpb437oXT/e1PSMbKdcebgMxuPH6eM=,iv:z5OjO7+mmQTsQ+nz6x6h7806R+l28ceiXC1V9XANiTQ=,tag:48+7j4skrEh8iAKrcfRiJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
