---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall
  namespace: heimdall
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi