---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: guacd
   namespace: guacd
spec:
  selector:
    matchLabels:
      run: guacd
  replicas: 1
  template:
     metadata:
       labels:
         run: guacd
     spec:
        containers:
         - name: guacd
           image: guacamole/guacd:1.4.0
           resources:
             limits:
               cpu: "100M"
               memory: "128Mi"
             requests:
               cpu: "50M"
               memory: "64Mi"               
           ports:
           - containerPort: 4822