apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
    namespace: vpn
type: Opaque
stringData:
    tailscale-token: ENC[AES256_GCM,data:Lo1/42Lu84TkMLxfL1ifAMgHBbLgyqgqxdg1ex8xo7H/3LotFAJ+DYnW8+kfagJzLLKzGgzrg5M=,iv:w/5JTqyqyKuWHfrhuaCsPd8HUo06ocf7kGJtD3O7w3c=,tag:RxqSW963V1TbByXOz3WpCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OU8xYmxxMklJVGZGanZ6
            bXV0Qkd6NTQ5d0ZzOTQ5eUY3SDY5T0NJWEVvCkZtWUlYL0ZwSW9WR280UzZWNk9y
            SS9sc2RkUUpTZFAwcnpNdzIyQ1ZlOEkKLS0tIE5Cb29HelJmaER2b0prb2xGaXM5
            OVhjdGcwUWtRZGRYSXlUTlI3eU9IUmcKAt1hBEIkRq8r0yGTiGNfeNUnCTjVwvt1
            UUpuUykHQUPnWRlAUDC0WUh17xZCEqjxYSAAQEh7LLQf3ePSPWK9TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T12:03:30Z"
    mac: ENC[AES256_GCM,data:KKy/bbHp1O3BU+ZHqqxai5iJKZErAQ4ZwHnmvWU/KJtCrR2LW4fiJNmmxtDlFDRgebdK0pqsPPl49st7XoFp/9VuN+O7fdiXRLVIyJy2gxt5BO1SPIZy6l7gDdBFwLPexMTgWeXORux8H0Yn/zaK5caSjyBjnCHzG0jsl/HiAEI=,iv:/Q/5FMkY6seRnjtpI0HGx9qLRluW/SBVus7Wlb7PEew=,tag:les7jHta9qE9/yJr4GOoHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
