# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    SECRET_INT_DOMAIN: ENC[AES256_GCM,data:8dHqGvzDmhwpkeOX3Ul64J4=,iv:9ZiWpZR2JR4ibW0AFvZocaObNrxK0mLFleYY1AfXs2s=,tag:ubYVDylrNUUg12JOgw+hGA==,type:str]
    SECRET_INT_CERT_DOMAIN: ENC[AES256_GCM,data:Op7qCcpOYd5p/hSDAP6CFSU=,iv:lXPFI3DlAXQRfe3yLp9txVoockWJeI5586j3uu9YkTE=,tag:D33uBZzQA4J96Vp/7Xe8PQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSURVV1VMT3BxV1c2SzNX
            Q0thTGZzaDFnbm9QRlBOYjNUOVRSQ2hMYVJVCkx6OE5oMXA0MTQ5MzVZSTFKZVU4
            cWV3c1R2TWlQOFBrWWJReTNPUWtLWFEKLS0tIEwzRmFtL2lGdFhteVJ0WjFsaVFE
            WFNmdFl5Nzd1Wk9scVBvUktJd3lPUXMKgKip8dJGj0wZeUKeQD5rMXuF/i3Lrrnh
            5fmxGoJgVQfRpWE3c2Dts5yag1Ls9aNIClUMT18fClDMpauL9eI6bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-11T11:51:53Z"
    mac: ENC[AES256_GCM,data:hzv7t7BydrfdS5VfSnFVmpC6xy8evu1GGu8Afgd4nHGzlf6RIFDcBph/nsEqbPMyM+gKjhFxihpIMe4i8mXpeifQhaCH/I3Eh7T1oXcTm4hM2cfDIBuXT+FCXBwELqeORpQ2DVm7ZhyRbytOrXoeG7x4/dYAORZJEaQD0yDWrhU=,iv:YDYW+13aBj2ZbAi+LRr90cw37s6TDzGvf/nJwI91agA=,tag:5sqBiP/Y8VpJWPiZ8yj22A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
