# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    SECRET_INT_DOMAIN: ENC[AES256_GCM,data:8dHqGvzDmhwpkeOX3Ul64J4=,iv:9ZiWpZR2JR4ibW0AFvZocaObNrxK0mLFleYY1AfXs2s=,tag:ubYVDylrNUUg12JOgw+hGA==,type:str]
    SECRET_INT_CERT_DOMAIN: ENC[AES256_GCM,data:Op7qCcpOYd5p/hSDAP6CFSU=,iv:lXPFI3DlAXQRfe3yLp9txVoockWJeI5586j3uu9YkTE=,tag:D33uBZzQA4J96Vp/7Xe8PQ==,type:str]
    SECRET_AWS_BUCKET: ENC[AES256_GCM,data:qoamqRLeyBAKKIm+TgBwWD6HcvR4JN4uKa5AJZAwTuyoqMf0LXE=,iv:r7rXLlXcj1Q49j2lVO/EH01r9Yi3rJn4e6TMsqUIag8=,tag:lnu0hoqlgNKiEhYDIKbPUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSURVV1VMT3BxV1c2SzNX
            Q0thTGZzaDFnbm9QRlBOYjNUOVRSQ2hMYVJVCkx6OE5oMXA0MTQ5MzVZSTFKZVU4
            cWV3c1R2TWlQOFBrWWJReTNPUWtLWFEKLS0tIEwzRmFtL2lGdFhteVJ0WjFsaVFE
            WFNmdFl5Nzd1Wk9scVBvUktJd3lPUXMKgKip8dJGj0wZeUKeQD5rMXuF/i3Lrrnh
            5fmxGoJgVQfRpWE3c2Dts5yag1Ls9aNIClUMT18fClDMpauL9eI6bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T17:09:05Z"
    mac: ENC[AES256_GCM,data:AjEgp71pT69+p/vuGPNCJRZ0gIo0ipgF1gPbGZ8ehVe0HmWgzWR1ErFSEL7y0F7HshIitNmyffn8AbF0hB74pJzki+CoGbXJnbQlTiQoztaXTJoKrwpC+ONU3DSKonWL+suq3MSu5yxTAg/W5yLHsWl5zwnyCPImzrAS6K8VAZI=,iv:111laOoYCHu1O4vDV3MLvB61diSWyWulMWsAda2Xt5A=,tag:BqD7k+038t2bvEtMPD3Hgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
