# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    SECRET_INT_DOMAIN: ENC[AES256_GCM,data:8dHqGvzDmhwpkeOX3Ul64J4=,iv:9ZiWpZR2JR4ibW0AFvZocaObNrxK0mLFleYY1AfXs2s=,tag:ubYVDylrNUUg12JOgw+hGA==,type:str]
    SECRET_INT_CERT_DOMAIN: ENC[AES256_GCM,data:Op7qCcpOYd5p/hSDAP6CFSU=,iv:lXPFI3DlAXQRfe3yLp9txVoockWJeI5586j3uu9YkTE=,tag:D33uBZzQA4J96Vp/7Xe8PQ==,type:str]
    S3_Backup_Location: ENC[AES256_GCM,data:taekXWjJLqoiH1mQdyuQpD4i7hzMIH+CA+Zr2kBPhe5Kx39H8ns=,iv:Fieo0GgIdb9bRRY7BtiMkdjwygYZS8gf9W1pviPr/yU=,tag:WgQnoSb6sCIT+1czQdnqwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSURVV1VMT3BxV1c2SzNX
            Q0thTGZzaDFnbm9QRlBOYjNUOVRSQ2hMYVJVCkx6OE5oMXA0MTQ5MzVZSTFKZVU4
            cWV3c1R2TWlQOFBrWWJReTNPUWtLWFEKLS0tIEwzRmFtL2lGdFhteVJ0WjFsaVFE
            WFNmdFl5Nzd1Wk9scVBvUktJd3lPUXMKgKip8dJGj0wZeUKeQD5rMXuF/i3Lrrnh
            5fmxGoJgVQfRpWE3c2Dts5yag1Ls9aNIClUMT18fClDMpauL9eI6bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T16:22:27Z"
    mac: ENC[AES256_GCM,data:I2oV1cOLtYfcdfsH58EgMO0iP06iLrzXvCyjLwzxDhwTJFaeJAgBYfdHqJS+n2X1I06+N5P2sDFSMcRqhwXpuROl48XKaEDTLMR3yogf7cOEwgsNIxM/h6fPqV2Wu6KuqsRxOFECe3Mk/To3RKPJj5OZ1QZUuZSqeuKDLIFg4Yg=,iv:XQTSbqzElmwkQHlwgQbZYewqvR6Ax8hmFHRsU9NAkz8=,tag:ObFj9qBMwXX7JJLiPrFDNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
