apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:qs6/ryEjHP003kpM,iv:/EI2t10xrbnu9Aq9UIk7iFcl7E3GMvSVLSQ5wNTPa0A=,tag:OZeOG439TBGURKfdWLlR5w==,type:str]
    admin-user: ENC[AES256_GCM,data:7ST8Vqj5gVY=,iv:WrKGyp6XCmanJbgEIZELk7mlg0wfc1w0lVc+RNc3vUo=,tag:qFxi1ThESaQeNpSaopYnng==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLemE5Qlpobkw2NERCbUZZ
            T08zOEYzTzZYajg0RGV2cGtoQk0xN2FhWTE0CkhVZ0JtRFhyYkVtcDBMalZNSUpk
            ZE1hNjl6S243ZTVzVUtMOGdEMlNYK2sKLS0tIGVqY2orclBnRlBvZFEvMWFjVTVs
            WE40UlBKQ1J5V2pDc3dXYnZIWEdreU0KAdHJBj9P+Yk7c3o5KU+NdvwF6QenwC5Y
            M7cHmiI8HiDcoe7jgi6PT5cg+up4Z5v/sa+rqbS7+XKFMjKza1Nnlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T20:00:42Z"
    mac: ENC[AES256_GCM,data:ETxbiL2LjcyAuW6H3DaNSnKe9iuywYPFmlDszBhNK690Oe4IYKrrGCUPeHlDN1aDQirLNe/Kwti4vrjLEubcMdbd85vGs82EtZcbx/+5L5mU5uCQ/iX710dKPoYe+xpavUi6NcQ+OAe/m04v6gjm7+9vHA/SkKUN/yZ38J4gaPk=,iv:NKfFxyG8AHiAUYJaKgIdzNDqdSlc+1cY7J1GP8lokFk=,tag:ve1P86qSQW8vYnEvXtK1MQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
