apiVersion: v1
stringData:
    admin-password: ENC[AES256_GCM,data:mA0UJ3VwbA==,iv:Nsi0azL1zFhZKr1CNSyG7txgawd9pukIMOnGSqiZIlo=,tag:8jAGGSUiEE/Lg1C//da4Iw==,type:str]
    admin-user: ENC[AES256_GCM,data:9/zZdy4=,iv:RXTgvQ8ucxwef7zTQiln5G+YiHuva57Q4UZFktPMIcs=,tag:MU4uvFoQshUztroYuuEdOw==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: prometheus
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLemE5Qlpobkw2NERCbUZZ
            T08zOEYzTzZYajg0RGV2cGtoQk0xN2FhWTE0CkhVZ0JtRFhyYkVtcDBMalZNSUpk
            ZE1hNjl6S243ZTVzVUtMOGdEMlNYK2sKLS0tIGVqY2orclBnRlBvZFEvMWFjVTVs
            WE40UlBKQ1J5V2pDc3dXYnZIWEdreU0KAdHJBj9P+Yk7c3o5KU+NdvwF6QenwC5Y
            M7cHmiI8HiDcoe7jgi6PT5cg+up4Z5v/sa+rqbS7+XKFMjKza1Nnlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-30T13:07:20Z"
    mac: ENC[AES256_GCM,data:3TdNC69yjkg/ZWZt4/aF8lcvzGIH6/zzyQ3yBeNozbn1DAt2blpADEOSO0iwlr9kzTgPcd2FAsNWA7Qr8JzW50FcWhFbAtcZpW02yp7xO8ZO1xbwQdFDEQClkmVT6xA8y+JZb3tgaWMysvSMWH1d0zbQfksz4GrgN18bOlX3Ysk=,iv:42UkLGN28L41sfUB1MUDC6aDkVZUw+VkJjCA2R0kdJU=,tag:aBtAhfxji59agH4Ey+Tv+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
