---
galaxy_info:
  role_name: kubernets-patching
  author: John Limb
  description: Update and reboot Kubernetes nodes
  # If the issue tracker for your role is not on github, uncomment the
  license: BSD
  min_ansible_version: 4
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
  #
  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
  galaxy_tags:
    - kubernetes
dependencies: []
# List your role dependencies here, one per line.
# Be sure to remove the '[]' above if you add dependencies
# to this list.
