---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-config-pvc
  namespace: code-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-WS-pvc
  namespace: code-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
