apiVersion: v1
kind: ConfigMap
metadata:
    name: code-server-configmap
    namespace: code-server
data:
    PUID: "1000"
    PGID: "1000"
    TZ: London/Europe
    proxy_domain: code.${SECRET_INT_DOMAIN}
    default_workspace: /workspace
    DOCKER_MODS: linuxserver/mods:code-server-extension-arguments|ghcr.io/ivanmorenoj/lsio-mods:code-server-ws|linuxserver/mods:code-server-awscli|linuxserver/mods:code-server-terraform
    VSCODE_EXTENSION_IDS: vscodevim.vim|streetsidesoftware.code-spell-checker|mhutchie.git-graph|ms-kubernetes-tools.vscode-kubernetes-tools|redhat.vscode-yaml|vscode-icons-team.vscode-icons|eamodio.gitlens|signageos.signageos-vscode-sops-beta
