---
kind: Service 
apiVersion: v1 
metadata:
  name: code-server-ui-svc
  namespace: code-server
spec:
  selector:
    app: code-server
  type: ClusterIP
  ports:
    - name: ui-svc
      port: 80
      targetPort: 8443
      protocol: TCP